# tools.example.mk — copy to .agent/tools.local.mk to override defaults
#
# DO NOT EDIT THIS FILE. Copy it:
#   cp tools.example.mk .agent/tools.local.mk
# then edit your copy. The .local.mk is gitignored.
#
# The build harness picks a simulator in this order:
#   1. PATH lookup (default — works if you `source settings64.sh` first)
#   2. VLSI_SIM env var (e.g., VLSI_SIM=xsim, iverilog, vcs, xrun, vsim)
#   3. VLSI_SIM_BIN env var (full path to the bin directory)
#   4. .agent/tools.local.mk (this file's contents, if you set them)
#
# Variables you can override:
#
#   VLSI_SIM     — which simulator to use. One of:
#                    xsim     (Xilinx Vivado xsim)
#                    iverilog (Icarus Verilog — license-free, default in CI)
#                    vcs      (Synopsys VCS)
#                    xrun     (Cadence Xcelium)
#                    vsim     (Mentor/Siemens Questa/ModelSim)
#
#   VLSI_SIM_BIN — full path to the bin directory containing the simulator
#                    binaries. Only needed if the simulator is not on PATH.
#
# Example overrides (uncomment ONE block):
#
# # Vivado xsim (Windows or Linux)
# VLSI_SIM     := xsim
# VLSI_SIM_BIN := /opt/Xilinx/2024.2/Vivado/bin
#
# # Icarus Verilog (default if PATH already has it)
# VLSI_SIM     := iverilog
#
# # VCS
# VLSI_SIM     := vcs
# VLSI_SIM_BIN := /tools/synopsys/vcs/U-2023.03/bin
